apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langgraph-kafka.fullname" . }}-config
  labels:
    {{- include "langgraph-kafka.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.kafkaBootstrapServers | quote }}
  KAFKA_TOPIC: {{ .Values.env.kafkaTopic | quote }}
  KAFKA_INPUT_TOPIC: {{ .Values.env.kafkaTopic | quote }}
  KAFKA_OUTPUT_TOPIC: {{ .Values.env.kafkaResultsTopic | quote }}
  KAFKA_RESULTS_TOPIC: {{ .Values.env.kafkaResultsTopic | quote }}
  KAFKA_RESPONSE_TOPIC: {{ .Values.env.kafkaResultsTopic | quote }}
  LANGGRAPH_API_URL: {{ .Values.env.langgraphApiUrl | quote }}
  # LangSmith Tracing Configuration  
  LANGCHAIN_TRACING: {{ .Values.env.langchainTracing | quote }}
  LANGCHAIN_TRACING_V2: {{ .Values.env.langchainTracing | quote }}
  LANGCHAIN_ENDPOINT: {{ .Values.env.langchainEndpoint | quote }}